var maruf = 10;
console.log(maruf);
let tool = 'gfg';
console.log(tool);
const variable = 78.99;
console.log(variable);
console.log(Masum);
var Masum = 10;
console.log(Masum);
var typeNull = null;
console.log(typeNull);
var name = 'maruf';
console.log(name);
tool = 10;
console.log(tool);

maruf = 'Fazley';
console.log(maruf);
maruf = 'Atif';
console.log(maruf);
