var maruf = 10;
console.log(maruf);
let tool = 'gfg';
console.log(tool);
const variable = 78.99;
console.log(variable);
console.log(Masum);
var Masum;
console.log(Masum);
var typeNull = null;
console.log(typeNull);
